"'Developer Configuration Screen' As screen":
    Fill: =gblTheme.BodyBackground
    OnVisible: |
        =Set(
            gblShowSpinner,
            true
        );
        Patch(
            'Screen Use',
            Defaults('Screen Use'),
            {
                ApplicationName: gblAppGlobals.ApplicationName,
                Title: App.ActiveScreen.Name & " - " & Now(),
                ScreenName: App.ActiveScreen.Name,
                AppVersion: gblAppGlobals.AppVersion,
                UserEmail: Lower(User().Email),
                Info: "Collection Initialized - in App.OnStart!",
                SessionString: gblSessionText
            }
        );
        Set(
            gblShowSpinner,
            false
        );

    "'SCREEN HEADER_11' As compScreenHeader":
        BackgroundColor: =gblTheme.PrimaryLight
        Fill: ='SCREEN HEADER_11'.BackgroundColor
        Forecolor: =gblTheme.PrimaryLightFont
        Y: =100

    "'APP HEADER_14' As compAppHeader":
        ApplicationName: =gblAppGlobals.ApplicationName
        ColorPrimaryDark: =gblTheme.PrimaryDark
        ColorPrimaryDarkFont: =gblTheme.PrimaryLight
        Fill: ='APP HEADER_14'.ColorPrimaryDark
        LogoImage: =gblAppGlobals.ApplicationLogo
        ProfileLine1: =gblCurrentUser.FullName
        ProfileLine2: =gblCurrentUser.Email
        ProfilePhoto: =gblCurrentUser.Photo
        ZIndex: =2

    icoShowDebug_6 As icon.Add:
        Color: =If(gblShowDebugging, gblTheme.PrimaryLight, ColorFade(gblTheme.PrimaryDark, 10%))
        Height: =45
        Icon: =Icon.Printing3D
        OnSelect: =Set(gblShowDebugging, !gblShowDebugging);
        Visible: =gblIsTester
        Width: =45
        X: =gblAppGlobals.DebugButton_X
        Y: =gblAppGlobals.DebugButton_Y
        ZIndex: =3

    "'SPINNER GROUP_11' As group":
        Height: =5
        Width: =5
        X: =40
        Y: =40
        ZIndex: =3

        recSpinner_11 As rectangle:
            Fill: =RGBA(255, 255, 255, 0.85)
            Height: =768
            Visible: =gblShowSpinner
            Width: =1366
            ZIndex: =9

        imgSpinner_12 As image:
            BorderColor: =White
            BorderStyle: =BorderStyle.Dashed
            Height: =206
            Image: =gblTheme.Spinner
            Visible: =gblShowSpinner
            Width: =206
            X: =Parent.Width / 2 - Self.Width / 2
            Y: =321
            ZIndex: =10

    imgFemaleProfilePhoto As image:
        Height: =200
        Image: =FemaleProfilePhoto
        Width: =200
        X: =583
        Y: =549
        ZIndex: =4

    Image2 As image:
        BorderColor: =gblTheme.PrimaryLight
        BorderThickness: =4
        Fill: =gblTheme.PrimaryDark
        Height: =185
        Image: =Logo
        PaddingBottom: =20
        PaddingTop: =20
        Width: =541
        X: =804
        Y: =564
        ZIndex: =5

    Label2 As label:
        Color: =gblTheme.PrimaryDark
        Height: =59
        Text: ="These images are needed for the demo mode. "
        Width: =541
        X: =804
        Y: =505
        ZIndex: =6

    Label1_12 As label:
        BorderColor: =gblTheme.PrimaryDark
        BorderStyle: =BorderStyle.Dotted
        BorderThickness: =1
        Color: =gblTheme.PrimaryDark
        Fill: =LightYellow
        Text: ="Testing..."
        Visible: =gblShowDebugging
        Width: =100
        X: =gblAppGlobals.DebugButton_X - Self.Width - 10
        Y: =gblAppGlobals.DebugButton_Y + 4
        ZIndex: =7

    "'SIDE NAV_11' As compSideNavMenu":
        BackgroundColor: =gblTheme.MenuBackcolor
        Fill: ='SIDE NAV_11'.BackgroundColor
        ForegroundColor: =gblTheme.MenuForecolor
        GroupsUserIsIn: =gblUserRoles
        IconsOrImages: =varGlobalMenuSettings.IconsOrImages
        MenuItems: =colNavItems
        ShowDottedOutline: =varGlobalMenuSettings.ShowDottedOutline
        Width: =If('SIDE NAV_11'.IsExpanded, 450, 80)
        Y: =100
        ZIndex: =8

